steps:
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ancient-ship-484917-e5/kanban-project/frontend:latest'
      - '.'
    

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/ancient-ship-484917-e5/kanban-project/frontend:latest'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'
    env:
     - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
     - 'CLOUDSDK_CONTAINER_CLUSTER=kanban-project'
     - 'CLOUDSDK_CORE_PROJECT=ancient-ship-484917-e5'

options:
  logging: CLOUD_LOGGING_ONLY
